FROM node:10-alpine
WORKDIR /dist
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY ./dist/jobs jobs/.
COPY ./dist/lib lib/.
RUN npm install
CMD [ "node", "jobs/server.js" ]