FROM node:10-alpine
WORKDIR /dist/api
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY ./dist/api .
RUN npm install
ARG PORT
ENV PORT $PORT
EXPOSE $PORT
CMD [ "node", "server.js" ]